### PR TITLE
Fix handler path separator on windows

### LINKED ISSUE #75: Handler path separator incorrect on windows
The Lambda handler path is set using path.join which uses the native system path separator.  Using the windows path separator causes lambda to fail to import the handler.

### PR DESCRIPTION
**Pull request by justin-gerhardt**
fixes #75

### CODE REVIEW

**Comment by pselle** [comment]
Thank you for the PR @justin-gerhardt! I'm seeing if one of our Windows users can validate that the tests still pass on a Windows machine (since our automated tests run on Linux). Thanks again! :+1:

**Comment by fastfiveoh** [comment]
@justin-gerhardt I am attempting to validate this locally on a Windows dev box I set up.  Can you describe your dev env for me?  I am running into some issues with dependency compatibility running in Windows and the sls invoke is failing.

**Comment by justin-gerhardt** [comment]
I can't say i've run into any issues. I'm running on windows 10 1803 x64
To build the iopipe plugin.

1. clone the repo
2. ran npm install
3. mkdir dist
4. npm run webpack
5. node .\node_modules\uglify-es\bin\uglifyjs dist\index.js --output dist\index.js --beautify

the deploy environment:
node 9.10.1 (locally, target node 8.10)
serverless 1.27.3.

plugins (loaded in this order)
serverless-plugin-iopipe
 serverless-plugin-typescript (with [this patch](https://github.com/prismagraphql/serverless-plugin-typescript/pull/79) to deal with iopipe generating js files)
serverless-offline-scheduler
serverless-offline-sns
serverless-offline

these are my project dependency (I had to make some small local changes to the serverless plugins so they are installed separately):
```
"devDependencies": {
    "@types/aws-lambda": "^8.10.5",
    "@types/jsonwebtoken": "^7.2.7",
    "@types/luxon": "^0.5.2",
    "@types/node": "^8.10.18",
    "@types/uuid": "^3.4.3",
    "@types/xml2js": "^0.4.2",
    "aws-lambda": "^0.1.2",
    "aws-sdk": "^2.248.1",
    "body-parser": "^1.18.3",
    "express": "^4.16.3",
    "fs-extra": "^6.0.1",
    "globby": "^8.0.1",
    "lodash": "^4.17.10",
    "lodash.assignin": "^4.2.0",
    "lodash.clonedeep": "^4.5.0",
    "lodash.startcase": "^4.4.0",
    "node-fetch": "^2.1.2",
    "node-schedule": "^1.3.0",
    "serverless-offline": "^3.23.1",
    "typescript": "^2.9.1",
    "xml": "^1.0.1"
  },
  "dependencies": {
    "@sendgrid/mail": "^6.2.1",
    "aws-auth-policy": "^0.1.0",
    "axios": "^0.18.0",
    "bluebird": "^3.5.1",
    "busboy": "^0.2.14",
    "google-auth-library": "^1.5.0",
    "googleapis": "^29.0.0",
    "http-status-codes": "^1.3.0",
    "jsonwebtoken": "^8.2.1",
    "luxon": "^1.2.1",
    "mysql2": "^1.5.3",
    "qs": "^6.5.2",
    "reflect-metadata": "^0.1.12",
    "typeorm": "^0.2.6",
    "uuid": "^3.2.1",
    "xml2js": "^0.4.19"
  }

```
I've never tried to use sls invoke but noticed no issues after deploying

**Comment by fastfiveoh** [comment]
@justin-gerhardt  Tested on a fresh Windows 10 dev box, with all dependencies used.  Cloned your repo, set with `patch-1` branch.  Confirmed using your code branch in my test directory `import { join, posix } from 'path';` and ` posix.join(handlerDir, `${obj.name}-${index}-iopipe.${obj.name}`)` were in the code for `serverless-plugin-iopipe`

However for me it still fails to detect/import the handler.  In my case the handler being `index.handlerTestChange`

When deploying, the function wraps properly however uses the erroneous handler:
image

Let me know if you have thoughts, I will bring this to my lead devs tomorrow.

**Comment by justin-gerhardt** [comment]
To clarify the issue your having is that the handler points to the wrong function? 
The path separator in your image are what it is supposed to be. 
Without the patch I get this path:
061290311c049e10cb0150714c86afa4
and after the patch I get this one:
af1ae74111de985ded9900040de3c4ca
The first can't be required and causes lambda to fail the second is working fine for me.

**Comment by fastfiveoh** [comment]
@justin-gerhardt thanks for pointing that out, looks like i have another issue with my environment.

I can confirm the operator change from `\` to `/` from master branch to patch-1 branch is working as intended, will close this PR.

**Comment by coreylight** [comment]
Thank you for your contribution @justin-gerhardt!

**Pull request merged**
